/**
 * CrowdSystem - thousands of living ball-character fans with GPU instancing.
 *
 * The stadium GLB ships without fans; instead we load the 16 fan variant meshes
 * from KickdomFans_Library.glb and the placement table (fans_placement.json)
 * generated by the Blender build script, then draw every variant as ONE
 * InstancedMesh. Per-fan state (phase, energy, team) drives idle bobbing,
 * random jumps, a travelling "Mexican wave" and full-team goal celebrations.
 */
import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';

export type Team = 'red' | 'blue';

export interface FanPlacement {
  m: string;                 // mesh name in the library GLB
  t: Team;
  p: [number, number, number]; // Blender Z-up position (metres)
  r: number;                 // yaw (radians)
  s: number;                 // uniform scale
  row: number;
  deck: 'low' | 'up';
}

interface FanState {
  variant: string;
  index: number;
  x: number; y: number; z: number;
  yaw: number;
  scale: number;
  phase: number;
  speed: number;
  team: Team;
  angle: number;      // polar angle around the pitch, for the wave
  bouncy: number;     // 0..1 how much this fan jumps at idle
  energy: number;     // current excitement 0..1
}

interface Variant {
  mesh: THREE.InstancedMesh;
  count: number;
}

const _dummy = new THREE.Object3D();

export class CrowdSystem {
  readonly group = new THREE.Group();
  private variants = new Map<string, Variant>();
  private fans: FanState[] = [];
  private celebration: { team: Team; t: number; duration: number } | null = null;
  private wave: { t: number; speed: number; dir: number } | null = null;
  private lastWave = 0;
  /** seconds between spontaneous waves (0 = never) */
  autoWaveEvery = 38;

  constructor(library: THREE.Object3D, placements: FanPlacement[], opts: { castShadow?: boolean } = {}) {
    this.group.name = 'Crowd';
    // ---- 1. build a merged geometry + material array per variant
    const geoByName = new Map<string, { geometry: THREE.BufferGeometry; materials: THREE.Material[] }>();
    library.traverse((node) => {
      if (!node.name.startsWith('Lib_Fan_')) return;
      const meshes: THREE.Mesh[] = [];
      node.traverse((c) => { if ((c as THREE.Mesh).isMesh) meshes.push(c as THREE.Mesh); });
      if (!meshes.length) return;
      const geoms: THREE.BufferGeometry[] = [];
      const mats: THREE.Material[] = [];
      for (const m of meshes) {
        const g = m.geometry.clone();
        g.deleteAttribute('uv');
        g.deleteAttribute('uv1');
        g.deleteAttribute('color');
        if (!g.getAttribute('normal')) g.computeVertexNormals();
        m.updateWorldMatrix(true, false);
        // node-relative transform (library objects live at the origin, primitives may carry offsets)
        const rel = new THREE.Matrix4().copy(node.matrixWorld).invert().multiply(m.matrixWorld);
        g.applyMatrix4(rel);
        geoms.push(g);
        mats.push(Array.isArray(m.material) ? m.material[0] : m.material);
      }
      const merged = mergeGeometries(geoms, true);
      if (!merged) return;
      geoByName.set(node.name.replace(/\.\d+$/, ''), { geometry: merged, materials: mats });
    });

    // ---- 2. count placements per variant, create InstancedMeshes
    const counts = new Map<string, number>();
    for (const p of placements) counts.set(p.m, (counts.get(p.m) ?? 0) + 1);
    for (const [name, n] of counts) {
      const src = geoByName.get(name);
      if (!src) { console.warn('[Crowd] missing variant', name); continue; }
      const mesh = new THREE.InstancedMesh(src.geometry, src.materials, n);
      mesh.name = `Crowd_${name}`;
      mesh.castShadow = !!opts.castShadow && name.endsWith('LOD0');
      mesh.receiveShadow = false;
      mesh.frustumCulled = false;
      mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
      this.variants.set(name, { mesh, count: 0 });
      this.group.add(mesh);
    }

    // ---- 3. per-fan state
    for (const p of placements) {
      const v = this.variants.get(p.m);
      if (!v) continue;
      const [bx, by, bz] = p.p;
      this.fans.push({
        variant: p.m,
        index: v.count++,
        x: bx, y: bz, z: -by,               // Blender Z-up -> glTF Y-up
        yaw: p.r,
        scale: p.s,
        phase: Math.random() * Math.PI * 2,
        speed: 0.8 + Math.random() * 0.6,
        team: p.t,
        angle: Math.atan2(-by, bx),
        bouncy: Math.random() < 0.22 ? 0.4 + Math.random() * 0.6 : 0,
        energy: 0,
      });
    }
    this.update(0, 0);
  }

  get count() { return this.fans.length; }

  /** Whole team goes wild for `duration` seconds; the other side sinks. */
  celebrate(team: Team, duration = 7) {
    this.celebration = { team, t: 0, duration };
  }

  startWave(dir = 1) {
    if (this.wave) return;
    this.wave = { t: 0, speed: 1.15, dir };
    this.lastWave = 0;
  }

  update(dt: number, time: number) {
    // spontaneous waves keep the crowd alive between game events
    this.lastWave += dt;
    if (this.autoWaveEvery > 0 && !this.wave && !this.celebration && this.lastWave > this.autoWaveEvery) {
      this.startWave(Math.random() < 0.5 ? 1 : -1);
    }
    if (this.wave) {
      this.wave.t += dt;
      if (this.wave.t > (Math.PI * 2) / this.wave.speed + 1.5) this.wave = null;
    }
    let celebTeam: Team | null = null;
    let celebLevel = 0;
    if (this.celebration) {
      const c = this.celebration;
      c.t += dt;
      const k = c.t / c.duration;
      celebTeam = c.team;
      celebLevel = k < 0.08 ? k / 0.08 : k > 0.75 ? Math.max(0, 1 - (k - 0.75) / 0.25) : 1;
      if (k >= 1) this.celebration = null;
    }

    const waveAngle = this.wave ? (-Math.PI + this.wave.t * this.wave.speed) * this.wave.dir : 0;
    for (const f of this.fans) {
      // ---- excitement
      let target = f.bouncy * 0.35;
      if (celebTeam) target = celebTeam === f.team ? 0.75 + f.bouncy * 0.25 : -0.25;
      target *= celebTeam ? celebLevel : 1;
      f.energy += (target - f.energy) * Math.min(1, dt * 3);

      // ---- motion
      const t = time * f.speed + f.phase;
      let lift = 0.025 * Math.sin(t * 2.1);                                     // breathing bob
      let squash = 1;
      if (f.energy > 0) {
        const j = Math.abs(Math.sin(t * 5.2));
        lift += f.energy * 0.42 * j;                                             // jumps
        squash = 1 + f.energy * 0.09 * Math.sin(t * 5.2 * 2);
      } else if (f.energy < 0) {
        squash = 1 + f.energy * 0.12;                                            // slump when the other team scores
      }
      if (this.wave) {
        let d = f.angle - waveAngle;
        d = Math.atan2(Math.sin(d), Math.cos(d));
        const w = Math.max(0, 1 - Math.abs(d) / 0.35);
        lift += Math.sin(w * Math.PI) * 0.55;
      }
      const sway = 0.05 * Math.sin(t * 1.3) * (0.4 + f.energy);

      _dummy.position.set(f.x, f.y + lift, f.z);
      _dummy.rotation.set(0, f.yaw + sway, 0.04 * Math.sin(t * 1.7) * (0.3 + Math.max(0, f.energy)));
      _dummy.scale.set(f.scale / Math.sqrt(squash), f.scale * squash, f.scale / Math.sqrt(squash));
      _dummy.updateMatrix();
      this.variants.get(f.variant)!.mesh.setMatrixAt(f.index, _dummy.matrix);
    }
    for (const v of this.variants.values()) v.mesh.instanceMatrix.needsUpdate = true;
  }

  dispose() {
    for (const v of this.variants.values()) {
      v.mesh.geometry.dispose();
      (v.mesh.material as THREE.Material[]).forEach((m) => m.dispose());
    }
    this.variants.clear();
    this.fans = [];
  }
}
