export { MenuBar } from './MenuBar';
export { DesktopCanvas, type ViewMode } from './DesktopCanvas';
export { DesktopItem } from './DesktopItem';
export { InfoWindow } from './InfoWindow';
export { default as Dock } from './Dock';
export { DockItem } from './DockItem';
export { MadeWithBadge } from './MadeWithBadge';
export { PublicDesktop } from './PublicDesktop';
export { SettingsWindow } from './SettingsWindow';
export { PersonaLoginScreen, PersonaModeToggle, useVisitorPersona, type VisitorPersona } from './PersonaLoginScreen';
export { StatusWidget } from './StatusWidget';
export { StatusWidgetEditor } from './StatusWidgetEditor';
export { WorkbenchWindow } from './WorkbenchWindow';
export { CommentSection } from './CommentSection';
